### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by IgorMuchnik**

### CODE REVIEW

**Review by DmitryKhodakovsky — CHANGES_REQUESTED** [review]
Project does not compile, tests do not run.
`mvn clean test` throws an error:
```
EPRUPETW2288:IgorMuchnik dmitry_khodakovsky$ mvn clean test
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.epam:IgorMuchnik:jar:1.0-SNAPSHOT
[WARNING] 'dependencies.dependency.systemPath' for com.epam.tat.module4:calculator-1.0:jar should not point at files within the project directory, ${basedir}/src/test/resources/calculator-1.0.jar will be unresolvable by dependent projects @ line 68, column 25
[WARNING] 'dependencies.dependency.systemPath' for com.epam.tat.module4:calculator-1.0:jar refers to a non-existing file /Users/dmitry_khodakovsky/EPAM-Projects/training_center/spring-automation-2020/IgorMuchnik/src/test/resources/calculator-1.0.jar @ line 68, column 25
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ------------------------< com.epam:IgorMuchnik >------------------------
[INFO] Building IgorMuchnik 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.248 s
[INFO] Finished at: 2020-03-31T00:30:09+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project IgorMuchnik: Could not resolve dependencies for project com.epam:IgorMuchnik:jar:1.0-SNAPSHOT: Could not find artifact com.epam.tat.module4:calculator-1.0:jar:1.0 at specified path /Users/dmitry_khodakovsky/EPAM-Projects/training_center/spring-automation-2020/IgorMuchnik/src/test/resources/calculator-1.0.jar -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Review by DmitryKhodakovsky — CHANGES_REQUESTED** [review]
profile `multAndDiv` has failed tests

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
[ERROR] Tests run: 15, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.398 s <<< FAILURE! - in TestSuite
[ERROR] multiplyTwoDoubleNumbers(hw1.MultiplicationTest)  Time elapsed: 0.005 s  <<< FAILURE!
java.lang.AssertionError: Test failed because expected [444.444] but found [444.0]
        at hw1.MultiplicationTest.multiplyTwoDoubleNumbers(MultiplicationTest.java:42)

[ERROR] doubleDivisionByZero(hw1.DivisionTest)  Time elapsed: 0.002 s  <<< FAILURE!
java.lang.AssertionError: Expected Exception to be thrown, but nothing was thrown
        at hw1.DivisionTest.doubleDivisionByZero(DivisionTest.java:66)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   DivisionTest.doubleDivisionByZero:66 Expected Exception to be thrown, but nothing was thrown
[ERROR] hw1.MultiplicationTest.multiplyTwoDoubleNumbers(hw1.MultiplicationTest)
[INFO]   Run 1: PASS
[INFO]   Run 2: PASS
[ERROR]   Run 3: MultiplicationTest.multiplyTwoDoubleNumbers:42 Test failed because expected [444.444] but found [444.0]
[INFO] 
[INFO] 
[ERROR] Tests run: 13, Failures: 2, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.354 s
[INFO] Finished at: 2020-04-01T12:13:55+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project IgorMuchnik: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/dmitry_khodakovsky/EPAM-Projects/training_center/spring-automation-2020/IgorMuchnik/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by IgorMuchnik** [comment]
> profile `multAndDiv` has failed tests
> 
> ```
> [INFO] -------------------------------------------------------
> [INFO]  T E S T S
> [INFO] -------------------------------------------------------
> [INFO] Running TestSuite
> [ERROR] Tests run: 15, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.398 s <<< FAILURE! - in TestSuite
> [ERROR] multiplyTwoDoubleNumbers(hw1.MultiplicationTest)  Time elapsed: 0.005 s  <<< FAILURE!
> java.lang.AssertionError: Test failed because expected [444.444] but found [444.0]
>         at hw1.MultiplicationTest.multiplyTwoDoubleNumbers(MultiplicationTest.java:42)
> 
> [ERROR] doubleDivisionByZero(hw1.DivisionTest)  Time elapsed: 0.002 s  <<< FAILURE!
> java.lang.AssertionError: Expected Exception to be thrown, but nothing was thrown
>         at hw1.DivisionTest.doubleDivisionByZero(DivisionTest.java:66)
> 
> [INFO] 
> [INFO] Results:
> [INFO] 
> [ERROR] Failures: 
> [ERROR]   DivisionTest.doubleDivisionByZero:66 Expected Exception to be thrown, but nothing was thrown
> [ERROR] hw1.MultiplicationTest.multiplyTwoDoubleNumbers(hw1.MultiplicationTest)
> [INFO]   Run 1: PASS
> [INFO]   Run 2: PASS
> [ERROR]   Run 3: MultiplicationTest.multiplyTwoDoubleNumbers:42 Test failed because expected [444.444] but found [444.0]
> [INFO] 
> [INFO] 
> [ERROR] Tests run: 13, Failures: 2, Errors: 0, Skipped: 0
> [INFO] 
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  2.354 s
> [INFO] Finished at: 2020-04-01T12:13:55+03:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project IgorMuchnik: There are test failures.
> [ERROR] 
> [ERROR] Please refer to /Users/dmitry_khodakovsky/EPAM-Projects/training_center/spring-automation-2020/IgorMuchnik/target/surefire-reports for the individual test results.
> [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
> [ERROR] -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> ```

Yes, these F

**Comment by IgorMuchnik** [comment]
Yes, there are two bugs that tests have found:
1) unexpected rounding of a result of a division
2) unmanaged behavior of division by zero 

So that failures are OK

**Review by DmitryKhodakovsky — APPROVED** [review]
Accepted. Could be merged to the master branch

**Pull request merged**
